package com.app.repository;

public class Query {

	public final static String getStateByName = "SELECT *FROM STATEMASTER WHERE STATENAME=?";
	public final static String deleteStateById = "DELETE FROM STATEMASTER WHERE STATEID=?";
	public final static String updateStateByName = "UPDATE STATEMASTER SET stateName=? where stateName=?";
	public final static String getDistByStateName = "SELECT D.DISTID, D.DISTNAME FROM DISTRICTMASTER D INNER JOIN STATE_DIST_JOIN SDT ON SDT.DISTID = D.DISTID INNER JOIN STATEMASTER S ON S.STATEID = SDT.STATEID WHERE S.STATENAME = ?";
	public final static String updateDistNameByState = "UPDATE DISTRICTMASTER D INNER JOIN STATE_DIST_JOIN SDJ ON D.DISTID = SDJ.DISTID INNER JOIN STATEMASTER S ON SDJ.STATEID = S.STATEID SET D.DISTNAME=? WHERE S.STATENAME=? AND D.DISTNAME = ?";
	public final static String deleteDistrictNameByState = "DELETE D FROM DISTRICTMASTER D JOIN STATE_DIST_JOIN SDT ON SDT.DISTID = D.DISTID JOIN STATEMASTER S ON S.STATEID = SDT.STATEID WHERE S.STATENAME = ? AND D.DISTNAME = ?";
	public final static String getCityIdByCityName = "SELECT CM.CITYID FROM CITYMASTER CM INNER JOIN CITY_DIST_STATE_JOIN CDSJ ON CDSJ.CITYID = CM.CITYID WHERE CM.CITYNAME = ? AND CDSJ.STATEID = ? AND CDSJ.DISTID = ?";
	public final static String getAllCityNamesByDist = "SELECT C.CITYID, C.CITYNAME FROM CITYMASTER C JOIN CITY_DIST_STATE_JOIN CDSJ ON CDSJ.CITYID = C.CITYID JOIN DISTRICTMASTER DM ON DM.DISTID = CDSJ.DISTID JOIN STATEMASTER SM ON SM.STATEID = CDSJ.STATEID WHERE SM.STATENAME = ? AND DM.DISTNAME = ?";
	public final static String updateCityName = "UPDATE CITYMASTER SET CITYNAME = ? WHERE CITYID = ? ";
	public final static String deleteCityByName = "DELETE FROM CITYMASTER WHERE CITYNAME = ?";
	public final static String showAllWardCityWise = "SELECT W.WARDID,W.WARDNAME FROM WARDMASTER W INNER JOIN CITY_WARD_JOIN CWJ ON CWJ.WARDID = W.WARDID INNER JOIN CITYMASTER C ON C.CITYID = CWJ.CITYID WHERE CITYNAME = ?";
	public final static String updateWardName = "UPDATE  WARDMASTER SET WARDNAME = ? WHERE WARDID = ? ";
	public final static String deleteWardById = "DELETE FROM WARDMASTER WHERE WARDID = ?";
	public final static String addAminity = "INSERT INTO AMENITIESMASTER (AMITNAME) VALUES(?)";
	public final static String deleteProperty = "DELETE FROM PROPERTYMASTER WHERE";
	public final static String updatePropertyByName = "UPDATE PROPERTMASTER SET PROPERNAME WHERE ? ";
}
